// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoZqC10ifU3RsJ2mxjZSyBTq2ZO5HFiJo',
    appId: '1:1015085830270:web:e4b5612bbeae024c18c82f',
    messagingSenderId: '1015085830270',
    projectId: 'chico-ff',
    authDomain: 'chico-ff.firebaseapp.com',
    storageBucket: 'chico-ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUPDzlp6ZEaZ8-Y5fgc4YT6KZR5yDFn0k',
    appId: '1:1015085830270:android:593e1bcd5e7ec99a18c82f',
    messagingSenderId: '1015085830270',
    projectId: 'chico-ff',
    storageBucket: 'chico-ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUUf4LOPEF4SGqBlOXb6VXHkxP8_XXeUo',
    appId: '1:1015085830270:ios:1968063734e17ce418c82f',
    messagingSenderId: '1015085830270',
    projectId: 'chico-ff',
    storageBucket: 'chico-ff.appspot.com',
    iosBundleId: 'com.example.chicoFf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUUf4LOPEF4SGqBlOXb6VXHkxP8_XXeUo',
    appId: '1:1015085830270:ios:1968063734e17ce418c82f',
    messagingSenderId: '1015085830270',
    projectId: 'chico-ff',
    storageBucket: 'chico-ff.appspot.com',
    iosBundleId: 'com.example.chicoFf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoZqC10ifU3RsJ2mxjZSyBTq2ZO5HFiJo',
    appId: '1:1015085830270:web:efd07515a0263ee518c82f',
    messagingSenderId: '1015085830270',
    projectId: 'chico-ff',
    authDomain: 'chico-ff.firebaseapp.com',
    storageBucket: 'chico-ff.appspot.com',
  );
}
